export { default as orderRouter } from './orderRouter.js'
export { default as paymentRouter } from './paymentRouter.js'
export { default as productRouter } from './productRouter.js'
export { default as userRouter } from './userRouter.js'
export { default as uploadRouter } from './uploadRouter.js'