export { default as Home } from './Home/Home'
export { default as ProductDetail } from './Product/Detail/Detail'
export { default as Cart } from './Cart/Cart'
export { default as Signin } from './Signin/Signin'
export { default as Register } from './Register/Register'