export { default as Home } from './Home/Home'
export { default as ProductDetail } from './Product/Detail/Detail'
export { default as Cart } from './Cart/Cart'
export { default as Signin } from './Signin/Signin'
export { default as Register } from './Register/Register'
export { default as Shipping } from './Shipping/Shipping'
export { default as Payment } from './Payment/Payment'
export { default as PlaceOrder } from './PlaceOrder/PlaceOrder'
export { default as Order } from './Order/Order'
export { default as OrderHistory } from './Order/History/OrderHistory'
export { default as Profile } from './Profile/Profile'

export { default as AdminProductList } from './Admin/Product/ProductList'
export { default as AdminProductEdit } from './Admin/Product/ProductEdit'
export { default as AdminOrderList } from './Admin/Order/OrderList'

export { default as PrivateRoute } from './utils/PrivateRoute'
export { default as AdminRoute } from './utils/AdminRoute'